use_frameworks!

platform :ios, '9.0'

target 'FYFNameSpace_Example' do
  pod 'FYFNameSpace', :path => '../'

  target 'FYFNameSpace_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
